### ISSUE TITLE
Multiple failed to load source map warnings

### ISSUE THREAD

**Issue by rysujana** [prashantpalikhe/nuxt-ssr-lit#101]
**Describe the bug**
The warning arises when I use the nuxt-ssr-lit. Specifically, I get warnings related to the failure to load source maps when I configure the package as ['nuxt-ssr-lit', { litElementPrefix: ['acme-'] }] which is actually the default setting.

**To Reproduce**
1. Import nuxt-ssr-lit like usual
2. Define the module with default 'nuxt-ssr-lit'

**Expected behavior**
I would expect that the package works seamlessly without emitting warnings about source maps when correctly configured.

**Screenshots**
![image](https://github.com/prashantpalikhe/nuxt-ssr-lit/assets/85550554/c2978579-ca81-42f6-88a6-84bf76c069bf)

 - Nuxt version: [e.g. 3.7.0]
 - Browser Firefox & Chrome

**Additional context**
I would love to know if this is normal or not and whether they should be ignored.

**Comment by prashantpalikhe** [comment]
Hi @rysujana 

These warnings are harmless, although very annoying indeed. We definitely need to look into it, but it should not be blocking for you.

**Comment by prashantpalikhe** [comment]
Should be fixed with the latest Nuxt upgrade.
