### ISSUE TITLE
"Hydration value mismatch" during conditional rendering

### ISSUE THREAD

**Issue by xander-marjoram** [prashantpalikhe/nuxt-ssr-lit#155]
**Describe the bug**
When using the contents of an object prop to conditionally render elements, hydration fails due to a mismatch error.
A fuller description with a code example is available in this minimal reproduction:
https://github.com/xander-marjoram/nuxt-lit-ssr-issue-repro

**To Reproduce**
1. Clone the above repo.
2. Follow the readme instructions to install and set up.
3. Build and run the app.
4. You should see the hydration mismatch error in the browser console (screenshot below).

**Expected behavior**
When SSR is enabled, the prop should have the correct value when rendering on the client. Ideally, there should then be no mismatch, and hydration should succeed without error.

**Screenshots**
![2024-07-22 13_24_32](https://github.com/user-attachments/assets/b6ed6fd8-412f-4b02-bb19-1b6533e6483f) 

 - Nuxt version: `^3.12.3` (see `package.json` of linked repo for more deps).
 - Affects latest Chrome, Firefox, Safari, Edge.

**Comment by xander-marjoram** [comment]
In the render function, you can see that I am logging the value of the `propObject` prop. I made the following observations, which may be of interest:

| `ssr` value in Nuxt config | Server | Client |
| --- | --- | --- |
| `true` | Value logged correctly | `undefined` |
| `false` | n/a | Value logged correctly |

**Comment by prashantpalikhe** [comment]
@xander-marjoram I think this is related to this research I had done on hydration issue for complex object types with Vue.

Read more here

https://github.com/prashantpalikhe/nuxt-ssr-lit/issues/34#issuecomment-1325563509

**Comment by prashantpalikhe** [comment]
@xander-marjoram Vue has fixed the issue on their end that causes this hydration issue for us.

https://github.com/vuejs/core/issues/7203 

Can you please try again with the latest version of Vue

**Comment by xander-marjoram** [comment]
@prashantpalikhe Sorry for the delayed reply, this did manage to fix our issues! Thanks for letting me know
