### ISSUE TITLE
Using with dynamic web-components

### ISSUE THREAD

**Issue by WillH0lt** [prashantpalikhe/nuxt-ssr-lit#164]
I'm looking for a way to add web-components dynamically, either through `<component :is="..." />` or `:v-html="..."`. Vue renders the html after the plugin runs, so the plugin never sees the dynamically added web-components. Any suggestions to get web-components that are server-side-rendered _and_ dynamic?

**Comment by prashantpalikhe** [comment]
You can place the `<LitWrapper />` around the `<component :is />` yourself. That should work.

**Comment by WillH0lt** [comment]
That works! Thank you!
