### ISSUE TITLE
Update imports to use Nuxt 3 stable

### ISSUE THREAD

**Issue by steveworkman** [prashantpalikhe/nuxt-ssr-lit#39]
We should upgrade the library to use the nuxt 3 stable internals.

Changes in nuxt 3 stable make the DOM shim load incorrectly and things don't build.

Thankfully, Lit 2.6 with Lit-labs/SSR 3 is now out and with it comes changes that mean the `window` object is not registered. There's lots of changes to the DOM Shim and this now enables us to move to Nuxt 3 fully.

**Comment by prashantpalikhe** [comment]
Picking this up now...
